### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by SantamRC** [ieeesb-nitdgp/ResearchPortalFrontend#27]
- [x] Debug all warnings in console
- [x] Professor should not post project without setting department
- [ ] Templates for Research Statement
- [ ] Background Knowledge for Projects
- [ ] Tasks for Projects
- [ ] Research Profile for Teachers
- [ ] Tags Filtering
- [ ] Search Bar
- [x] Change Dashboard Avatar ( NK)
- [x] Implement Profile Avatar
- [ ] Change the Teacher Create Projects Fields ( Tags )
- [x] Protected Route
- [ ] Showing authentication error while trying to reset password

- [x] Not showing whether username already exists

- [x] Needs to highlight the fields that are showing the error. For example: If the same email has been used twice to sign up for 2 diff accounts, it must highlight the email field and show the error.

- [ ] Doesn’t Show password strength

- [ ] Not being able to upload profile pic in the dashboard under the profile section

- [ ] Not showing the pdf or file being uploaded in the resume section under the profile section.

- [ ] The button beside the uploaded file is not working, hence it is not showing the file being uploaded.

- [ ] Not confirming whether an email is being sent from the contact us section, instead is just reloading the page.

- [ ] Deleted files are not being deleted from server

- [x] Update button not working properly. When trying to update a field, it is showing the previously filled info but reloading more than once will show the updated info.

- [x] If the project list is empty then it keeps on loading instead of showing that it's empty.

- [ ] While searching for projects through a student profile, the project list keeps on buffering even if some projects have been added.

- [ ] Option for draft and published not included in frontend.(for uploading project )

- [ ] No option to upload any doc for the project 

- [x] SOP upload not working

- [x] Not showing the project in the dashboard even after applying for it

**Comment by UdayanMukherjee** [comment]
- [ ] Showing authentication error while trying to reset password

- [ ] Not showing whether username already exists

- [ ] Needs to highlight the fields that are showing the error. For example: If the same email has been used twice to sign up for 2 diff accounts, it must highlight the email field and show the error.

- [ ] Doesn’t Show password strength

- [ ] Not being able to upload profile pic in the dashboard under the profile section

- [ ] Not showing the pdf or file being uploaded in the resume section under the profile section.

- [ ] The button beside the uploaded file is not working, hence it is not showing the file being uploaded.

- [ ] Not confirming whether an email is being sent from the contact us section, instead is just reloading the page.

- [ ] Deleted files are not being deleted from server

- [ ] Update button not working properly. When trying to update a field, it is showing the previously filled info but reloading more than once will show the updated info.

- [ ] If the project list is empty then it keeps on loading instead of showing that it's empty.

- [ ] While searching for projects through a student profile, the project list keeps on buffering even if some projects have been added.

- [ ] Option for draft and published not included in frontend.(for uploading project )

- [ ] No option to upload any doc for the project 

- [ ] SOP upload not working

- [ ] Not showing the project in the dashboard even after applying for it
